/**
 * Nurses Inc. — Laboratory Reference (clinician-grade).
 *
 * Used by the "Labs" sub-tab in the Definitions section on /forms.
 *
 * AUDIENCE: LPNs, RNs, partner physicians, pharmacists.
 *
 * Each entry includes:
 *  - acronym + full name
 *  - one-line description of what the cell / analyte does
 *  - body system
 *  - why it is useful
 *  - reasons it might be ordered
 *  - reference range (typical Canadian / NB units)
 *  - what LOW means
 *  - what HIGH means
 *
 * ⚠️ Always compare to your lab's specific reference range, which
 * can vary by method, instrument, and population. Ranges below are
 * adult reference ranges — pediatric and pregnancy ranges differ.
 * Last reviewed Aug 2026.
 */

export type LabSystem =
  | 'hematology'
  | 'coagulation'
  | 'metabolic'
  | 'renal'
  | 'hepatic'
  | 'lipid'
  | 'thyroid'
  | 'glucose'
  | 'iron'
  | 'inflammation'
  | 'cardiac'
  | 'vitamins'
  | 'electrolytes'
  | 'urine'
  | 'microbiology'
  | 'serology'
  | 'toxicology';

export type LabEntry = {
  id: string;
  acronym: string;
  fullName: string;
  system: LabSystem;
  description: string;
  purpose: string;
  indications: string[];
  range: string;
  low: string;
  high: string;
  notes?: string;
};

export const labReference: LabEntry[] = [
  // ============================================================
  // HEMATOLOGY — CBC + related
  // ============================================================
  {
    id: 'cbc',
    acronym: 'CBC',
    fullName: 'Complete Blood Count',
    system: 'hematology',
    description: 'Automated panel of red cells, white cells, platelets, and their indices.',
    purpose: 'Most common screening panel — assesses anemia, infection, inflammation, marrow function.',
    indications: [
      'Routine health screening',
      'Anemia workup',
      'Suspected infection',
      'Bleeding or bruising',
      'Pre-operative assessment',
      'Monitoring chemotherapy',
    ],
    range: 'See individual components (Hb, Hct, WBC, platelets, etc.)',
    low: 'See individual components.',
    high: 'See individual components.',
  },
  {
    id: 'hemoglobin',
    acronym: 'Hb / Hgb',
    fullName: 'Hemoglobin',
    system: 'hematology',
    description: 'Oxygen-carrying protein inside red blood cells.',
    purpose: 'Core anemia / polycythemia screening.',
    indications: [
      'Anemia workup (fatigue, pallor, dyspnea)',
      'Routine pre-operative assessment',
      'Monitoring chronic kidney disease',
      'Suspected blood loss (GI bleed, menorrhagia)',
      'Polycythemia workup',
      'Monitoring chemotherapy / immunosuppression',
    ],
    range: 'Male: 130–170 g/L · Female: 120–160 g/L',
    low: 'Anemia — iron deficiency, B12 / folate deficiency, chronic disease, hemolysis, blood loss. Correlate with MCV and ferritin.',
    high: 'Polycythemia — primary (polycythemia vera) or secondary (smoking, chronic hypoxia, dehydration, EPO-producing tumours).',
  },
  {
    id: 'hct',
    acronym: 'Hct',
    fullName: 'Hematocrit',
    system: 'hematology',
    description: 'Volume of red blood cells as a percentage of total blood volume.',
    purpose: 'Tracks with hemoglobin — confirms anemia / polycythemia and assesses IV fluid status.',
    indications: ['Anemia / polycythemia workup', 'Pre-op', 'Dehydration assessment'],
    range: 'Male: 0.40–0.52 L/L · Female: 0.36–0.48 L/L',
    low: 'Anemia (same causes as low hemoglobin).',
    high: 'Polycythemia or dehydration.',
  },
  {
    id: 'rbc',
    acronym: 'RBC',
    fullName: 'Red Blood Cell Count',
    system: 'hematology',
    description: 'Absolute count of red blood cells per unit volume.',
    purpose: 'Part of CBC — supports hemoglobin and hematocrit interpretation.',
    indications: ['Anemia workup', 'Polycythemia workup'],
    range: 'Male: 4.4–5.9 × 10¹²/L · Female: 3.8–5.2 × 10¹²/L',
    low: 'Anemia from any cause.',
    high: 'Polycythemia, dehydration.',
  },
  {
    id: 'wbc',
    acronym: 'WBC',
    fullName: 'White Blood Cell Count',
    system: 'hematology',
    description: 'Total count of infection- and immunity-fighting leukocytes in the blood.',
    purpose: 'Screens for infection, inflammation, marrow disorders, and immunosuppression.',
    indications: [
      'Suspected infection (bacterial / viral / fungal)',
      'Fever of unknown origin',
      'Monitoring chemotherapy',
      'Leukemia / lymphoma workup',
    ],
    range: '4.0–11.0 × 10⁹/L',
    low: 'Leukopenia — viral infection, chemotherapy, marrow suppression, SLE, severe sepsis, B12 / folate deficiency.',
    high: 'Leukocytosis — bacterial infection, inflammation, steroids, smoking, leukemia, stress response.',
  },
  {
    id: 'platelet',
    acronym: 'Plt',
    fullName: 'Platelet Count',
    system: 'hematology',
    description: 'Count of cell fragments that form clots to stop bleeding.',
    purpose: 'Critical for bleeding / clotting risk assessment.',
    indications: [
      'Pre-operative assessment',
      'Bruising / bleeding workup',
      'Monitoring chemotherapy',
      'Heparin-induced thrombocytopenia check',
      'ITP / TTP workup',
    ],
    range: '150–400 × 10⁹/L',
    low: 'Thrombocytopenia — ITP, TTP, chemotherapy, viral infection, cirrhosis, DIC. Bleeding risk if < 50; spontaneous bleeding if < 10.',
    high: 'Thrombocytosis — reactive (infection, iron deficiency, post-splenectomy) or myeloproliferative (ET, PV, CML, myelofibrosis).',
  },
  {
    id: 'mpv',
    acronym: 'MPV',
    fullName: 'Mean Platelet Volume',
    system: 'hematology',
    description: 'Average size of platelets.',
    purpose: 'Larger platelets are younger and more reactive. Useful in platelet disorders.',
    indications: ['Platelet disorder workup', 'ITP monitoring'],
    range: '7.5–11.5 fL',
    low: 'Bone marrow suppression, some inherited platelet disorders.',
    high: 'ITP, Bernard-Soulier syndrome, hyperthyroidism.',
  },
  {
    id: 'mcv',
    acronym: 'MCV',
    fullName: 'Mean Corpuscular Volume',
    system: 'hematology',
    description: 'Average size of red blood cells.',
    purpose: 'Classifies anemia as microcytic, normocytic, or macrocytic.',
    indications: ['Anemia workup (always paired with Hb)'],
    range: '80–100 fL',
    low: 'Microcytic — iron deficiency, thalassemia, anemia of chronic disease (early), lead poisoning.',
    high: 'Macrocytic — B12 or folate deficiency, hypothyroidism, alcoholism, liver disease, certain drugs (methotrexate, hydroxyurea).',
  },
  {
    id: 'mch',
    acronym: 'MCH',
    fullName: 'Mean Corpuscular Hemoglobin',
    system: 'hematology',
    description: 'Average hemoglobin mass per red blood cell.',
    purpose: 'Supports microcytic / macrocytic anemia classification.',
    indications: ['Anemia workup'],
    range: '27–33 pg/cell',
    low: 'Iron deficiency, thalassemia, anemia of chronic disease.',
    high: 'Macrocytic anemia (B12, folate).',
  },
  {
    id: 'mchc',
    acronym: 'MCHC',
    fullName: 'Mean Corpuscular Hemoglobin Concentration',
    system: 'hematology',
    description: 'Concentration of hemoglobin inside red cells.',
    purpose: 'Detects cellular hydration disorders (hemoglobin hydration).',
    indications: ['Anemia workup', 'Hereditary spherocytosis workup'],
    range: '320–360 g/L',
    low: 'Iron deficiency, thalassemia.',
    high: 'Hereditary spherocytosis, autoimmune hemolytic anemia (cold agglutinin).',
  },
  {
    id: 'rdw',
    acronym: 'RDW',
    fullName: 'Red Cell Distribution Width',
    system: 'hematology',
    description: 'Variation in red blood cell size across the sample.',
    purpose: 'High RDW = mixed picture (early iron deficiency, mixed nutritional deficiencies, hemolysis).',
    indications: ['Anemia workup'],
    range: '11.5–14.5%',
    low: 'Not clinically significant.',
    high: 'Anisocytosis — early iron deficiency, mixed B12/iron deficiency, hemolysis, recent transfusion.',
  },
  {
    id: 'neutrophils',
    acronym: 'Neut',
    fullName: 'Neutrophils',
    system: 'hematology',
    description: 'Most abundant white blood cells — first responders to bacterial infection.',
    purpose: 'Core part of WBC differential — screens for infection and immunosuppression risk.',
    indications: ['Infection workup', 'Chemotherapy monitoring'],
    range: '2.0–7.5 × 10⁹/L (or 40–70% of WBC)',
    low: 'Neutropenia — chemotherapy, viral infection, marrow suppression. < 1.5 = significant; < 0.5 = severe (febrile neutropenia risk).',
    high: 'Neutrophilia — bacterial infection, inflammation, steroids, stress, leukemia.',
  },
  {
    id: 'anc',
    acronym: 'ANC',
    fullName: 'Absolute Neutrophil Count',
    system: 'hematology',
    description: 'Calculated count of neutrophils — used to assess infection risk.',
    purpose: 'Critical for infection risk in immunocompromised patients (chemo, transplant).',
    indications: [
      'Monitoring chemotherapy',
      'Immunosuppression risk stratification',
      'Febrile neutropenia workup',
    ],
    range: '2.0–7.5 × 10⁹/L',
    low: 'Neutropenia — high infection risk. < 1.5 = moderate; < 0.5 = severe (febrile neutropenia risk).',
    high: 'Neutrophilia — bacterial infection, inflammation, steroids, stress.',
  },
  {
    id: 'lymphocytes',
    acronym: 'Lymph',
    fullName: 'Lymphocytes',
    system: 'hematology',
    description: 'White cells that drive adaptive immunity (T cells, B cells, NK cells).',
    purpose: 'Part of WBC differential — screens for viral infection and lymphoproliferative disorders.',
    indications: ['Viral infection workup', 'Lymphoma / leukemia workup', 'HIV monitoring'],
    range: '1.0–4.0 × 10⁹/L (or 20–40% of WBC)',
    low: 'Lymphopenia — viral infection, HIV, immunosuppression, chemotherapy, autoimmune disease.',
    high: 'Lymphocytosis — viral infection (EBV, CMV, hepatitis), lymphocytic leukemia, pertussis.',
  },
  {
    id: 'monocytes',
    acronym: 'Mono',
    fullName: 'Monocytes',
    system: 'hematology',
    description: 'White cells that migrate into tissues to become macrophages.',
    purpose: 'Part of WBC differential — chronic inflammation and infection.',
    indications: ['Chronic infection workup', 'Autoimmune workup'],
    range: '0.2–0.8 × 10⁹/L (or 2–10% of WBC)',
    low: 'Not clinically significant.',
    high: 'Chronic inflammation, infection (TB, endocarditis), sarcoidosis, leukemia.',
  },
  {
    id: 'eosinophils',
    acronym: 'Eos',
    fullName: 'Eosinophils',
    system: 'hematology',
    description: 'White cells involved in allergic and parasitic responses.',
    purpose: 'Screens for allergic, parasitic, and certain autoimmune conditions.',
    indications: ['Asthma / atopy workup', 'Suspected parasitic infection', 'Drug rash'],
    range: '0.0–0.5 × 10⁹/L',
    low: 'Not clinically significant.',
    high: 'Eosinophilia — allergic conditions, parasitic infection, drug reaction, certain leukemias, eosinophilic granulomatosis with polyangiitis.',
  },
  {
    id: 'basophils',
    acronym: 'Baso',
    fullName: 'Basophils',
    system: 'hematology',
    description: 'White cells that release histamine and mediate allergic responses.',
    purpose: 'Part of WBC differential — screens for allergic and myeloproliferative disorders.',
    indications: ['Allergy workup', 'Myeloproliferative workup'],
    range: '0.0–0.2 × 10⁹/L',
    low: 'Not clinically significant.',
    high: 'Basophilia — chronic myeloid leukemia, polycythemia vera, allergic reactions, hypothyroidism.',
  },
  {
    id: 'esr',
    acronym: 'ESR',
    fullName: 'Erythrocyte Sedimentation Rate',
    system: 'inflammation',
    description: 'Rate at which red cells settle in a tube — slower in healthy blood, faster when inflammation increases plasma proteins.',
    purpose: 'Sensitive marker of chronic inflammation. Less specific than CRP but useful for chronic disease monitoring.',
    indications: [
      'Giant cell arteritis (temporal arteritis)',
      'Polymyalgia rheumatica',
      'Inflammatory disease activity',
      'Unexplained fever',
    ],
    range: 'Male: < 20 mm/h · Female: < 30 mm/h (age-dependent)',
    low: 'Not clinically significant (polycythemia, sickle cell, low fibrinogen).',
    high: 'Chronic inflammation — RA, IBD, vasculitis, malignancy, infection, multiple myeloma.',
  },
  {
    id: 'retic',
    acronym: 'Retic',
    fullName: 'Reticulocyte Count',
    system: 'hematology',
    description: 'Count of immature red blood cells released from the bone marrow.',
    purpose: 'Assesses bone marrow response to anemia — high in hemolysis / blood loss, low in marrow failure or nutritional deficiency.',
    indications: ['Anemia workup', 'Marrow response assessment', 'Hemolysis workup'],
    range: '25–85 × 10⁹/L (or 0.5–2.5%)',
    low: 'Marrow failure, B12 / folate deficiency (marrow can\u2019t make new RBCs properly).',
    high: 'Hemolysis, recent blood loss, response to iron / B12 / folate therapy.',
  },
  {
    id: 'fdp',
    acronym: 'FDP',
    fullName: 'Fibrin Degradation Products',
    system: 'coagulation',
    description: 'Fragments produced when fibrin is broken down by plasmin during clotting.',
    purpose: 'Marker of active clot formation and breakdown — used in DIC workup.',
    indications: ['DIC workup', 'Suspected pulmonary embolism', 'Thrombolytic therapy monitoring'],
    range: '< 5 mg/L',
    low: 'Not clinically significant.',
    high: 'DIC, PE, DVT, thrombolytic therapy, recent surgery, liver disease.',
  },
  {
    id: 'sickle-cell',
    acronym: 'Sickledex',
    fullName: 'Sickle Cell Screen',
    system: 'hematology',
    description: 'Screening test for hemoglobin S (sickle hemoglobin).',
    purpose: 'Diagnoses sickle cell trait or disease.',
    indications: ['Unexplained hemolytic anemia', 'Family history', 'Hemoglobinopathy workup', 'Newborn screening'],
    range: 'Negative',
    low: 'N/A',
    high: 'Sickle cell trait (Hb AS) or disease (Hb SS, Hb SC). Confirm with hemoglobin electrophoresis.',
  },
  {
    id: 'g6pd',
    acronym: 'G6PD',
    fullName: 'Glucose-6-Phosphate Dehydrogenase',
    system: 'hematology',
    description: 'Enzyme that protects red blood cells from oxidative damage.',
    purpose: 'Diagnoses G6PD deficiency — an inherited cause of hemolytic anemia triggered by certain drugs, foods (fava beans), or infections.',
    indications: ['Episodic hemolytic anemia', 'Neonatal jaundice', 'Family history', 'Black or Mediterranean ancestry'],
    range: 'Within reference range (lab-specific)',
    low: 'G6PD deficiency — episodic hemolysis triggered by oxidants (sulfa drugs, dapsone, primaquine, fava beans, infection).',
    high: 'Not clinically significant.',
  },
  // ============================================================
  // COAGULATION
  // ============================================================
  {
    id: 'pt-inr',
    acronym: 'PT / INR',
    fullName: 'Prothrombin Time / International Normalized Ratio',
    system: 'coagulation',
    description: 'Time in seconds for the blood to clot via the extrinsic pathway, normalized across labs.',
    purpose: 'Measures extrinsic and common pathway of coagulation. Used to monitor warfarin and assess liver synthetic function.',
    indications: [
      'Warfarin monitoring',
      'Pre-operative coagulopathy screen',
      'Liver failure assessment',
      'Vitamin K deficiency',
      'DIC workup',
    ],
    range: 'PT: 11–13.5 s · INR: 0.9–1.1 (off warfarin) · Therapeutic warfarin: 2.0–3.0 (most indications), 2.5–3.5 (mechanical mitral valve)',
    low: 'Not clinically significant (high vitamin K intake, OCP use).',
    high: 'Anticoagulation (warfarin, DOACs), liver failure, vitamin K deficiency, DIC, factor deficiency.',
  },
  {
    id: 'aptt',
    acronym: 'aPTT',
    fullName: 'Activated Partial Thromboplastin Time',
    system: 'coagulation',
    description: 'Time in seconds for blood to clot via the intrinsic pathway.',
    purpose: 'Used to monitor unfractionated heparin and screen for hemophilia / lupus anticoagulant.',
    indications: [
      'Heparin monitoring (unfractionated)',
      'Pre-operative coagulopathy screen',
      'Recurrent miscarriage workup (lupus anticoagulant)',
    ],
    range: '25–38 s',
    low: 'Not clinically significant.',
    high: 'Heparin, lupus anticoagulant, hemophilia A / B, factor deficiencies, vitamin K deficiency, liver disease.',
  },
  {
    id: 'fibrinogen',
    acronym: 'Fib',
    fullName: 'Fibrinogen',
    system: 'coagulation',
    description: 'Clotting factor made by the liver that becomes the fibrin mesh in clots.',
    purpose: 'Acute-phase reactant and clotting factor I. Low in DIC, liver failure, or dilutional coagulopathy.',
    indications: ['DIC workup', 'Liver failure assessment', 'Unusual bleeding'],
    range: '2.0–4.0 g/L',
    low: 'DIC, liver failure, dilutional coagulopathy (massive transfusion), congenital afibrinogenemia.',
    high: 'Acute-phase response — infection, inflammation, malignancy.',
  },
  {
    id: 'heparin',
    acronym: 'Hep',
    fullName: 'Heparin Level',
    system: 'coagulation',
    description: 'Direct measurement of unfractionated heparin concentration in plasma.',
    purpose: 'Used to titrate IV heparin infusion to therapeutic range.',
    indications: ['Monitoring IV unfractionated heparin', 'Confirming anticoagulation on cardiopulmonary bypass'],
    range: '0.3–0.7 IU/mL (therapeutic, on infusion)',
    low: 'Subtherapeutic — thrombosis risk.',
    high: 'Supratherapeutic — bleeding risk. Hold infusion, monitor aPTT / anti-Xa, consider protamine reversal.',
  },
  {
    id: 'heparin-ab',
    acronym: 'Hep Ab',
    fullName: 'Heparin Antibody (anti-PF4)',
    system: 'coagulation',
    description: 'Antibody against the platelet factor 4 (PF4) — heparin complex that causes Heparin-Induced Thrombocytopenia (HIT).',
    purpose: 'Screens for HIT — a paradoxical prothrombotic condition caused by heparin exposure.',
    indications: ['Platelet count drop > 50% on heparin', 'New thrombosis on heparin', 'HIT clinical suspicion'],
    range: 'Negative',
    low: 'N/A',
    high: 'HIT — discontinue all heparin (including flushes). Start non-heparin anticoagulant (argatroban, bivalirudin, fondaparinux).',
  },
  {
    id: 'factor-v',
    acronym: 'Factor V Leiden',
    fullName: 'Factor V Leiden Mutation',
    system: 'coagulation',
    description: 'Genetic mutation in clotting factor V that makes it resistant to inactivation by protein C.',
    purpose: 'Screens for the most common inherited cause of thrombophilia.',
    indications: ['DVT / PE < 50 years old', 'Recurrent thrombosis', 'Family history of thrombosis', 'Unexplained pregnancy loss'],
    range: 'Negative (no mutation)',
    low: 'N/A',
    high: 'Heterozygous (4–8× risk) or homozygous (50–80× risk) Factor V Leiden — increased thrombosis risk on top of additional risk factors.',
  },
  {
    id: 'd-dimer',
    acronym: 'D-Dimer',
    fullName: 'D-Dimer',
    system: 'coagulation',
    description: 'Fibrin degradation product specific to cross-linked fibrin — marker of active clot breakdown.',
    purpose: 'Negative D-dimer helps rule out PE / DVT in low-probability patients. Positive is non-specific.',
    indications: ['Suspected PE', 'Suspected DVT', 'DIC workup', 'Aortic dissection workup'],
    range: '< 0.50 mg/L FEU (lab-specific)',
    low: 'N/A — useful when negative to rule out PE/DVT in low-risk patients.',
    high: 'PE, DVT, DIC, infection, inflammation, recent surgery, pregnancy, malignancy. False positives common — interpret with clinical probability score.',
  },
  // ============================================================
  // ELECTROLYTES
  // ============================================================
  {
    id: 'sodium',
    acronym: 'Na',
    fullName: 'Sodium',
    system: 'electrolytes',
    description: 'Main extracellular cation that controls fluid balance and blood pressure.',
    purpose: 'Reflects fluid balance. Critical for neurologic function.',
    indications: [
      'Dehydration / overhydration',
      'Confusion workup',
      'Seizure workup',
      'Diuretic monitoring',
      'SIADH / diabetes insipidus workup',
    ],
    range: '135–145 mmol/L',
    low: 'Hyponatremia — hypovolemic (diuretics, vomiting, diarrhea), euvolemic (SIADH, hypothyroid, adrenal insufficiency), hypervolemic (CHF, cirrhosis).',
    high: 'Hypernatremia — dehydration, diabetes insipidus, hyperosmolar states. Treat the cause, replace water slowly.',
  },
  {
    id: 'potassium',
    acronym: 'K',
    fullName: 'Potassium',
    system: 'electrolytes',
    description: 'Main intracellular cation that controls heart and muscle function.',
    purpose: 'Critical for cardiac and muscle function. Tightly regulated.',
    indications: [
      'Arrhythmia workup',
      'Diuretic monitoring',
      'Renal failure',
      'Muscle weakness',
      'Pre-operative',
      'Hypo- / hyperaldosteronism workup',
    ],
    range: '3.5–5.0 mmol/L',
    low: 'Hypokalemia — diuretics, vomiting, diarrhea, refeeding, hypomagnesemia. Cardiac arrhythmias risk. Replace before giving digitalis.',
    high: 'Hyperkalemia — renal failure, K-sparing diuretics, ACE-I/ARB, rhabdomyolysis, hemolysis, pseudohyperkalemia from hemolysis in the tube. ECG changes (peaked T waves) if ≥ 6.5 — urgent treatment.',
  },
  {
    id: 'chloride',
    acronym: 'Cl',
    fullName: 'Chloride',
    system: 'electrolytes',
    description: 'Main extracellular anion that pairs with sodium to balance fluid and acid-base.',
    purpose: 'Helps interpret acid-base and fluid status.',
    indications: ['Electrolyte panel', 'Acid-base assessment'],
    range: '98–107 mmol/L',
    low: 'Hypochloremia — vomiting, metabolic acidosis (renal tubular acidosis), diuretics.',
    high: 'Hyperchloremia — dehydration, metabolic acidosis (non-anion gap), saline infusion.',
  },
  {
    id: 'bicarbonate',
    acronym: 'HCO₃',
    fullName: 'Bicarbonate',
    system: 'electrolytes',
    description: 'Carbonate base that buffers the blood against acid build-up.',
    purpose: 'Used to interpret acid-base disorders.',
    indications: ['Acid-base assessment', 'Renal tubular acidosis', 'Chronic diarrhea'],
    range: '22–29 mmol/L',
    low: 'Metabolic acidosis — renal failure, DKA, lactic acidosis, diarrhea, RTA.',
    high: 'Metabolic alkalosis — vomiting, diuretics, hyperaldosteronism. Compensation for chronic respiratory acidosis.',
  },
  {
    id: 'magnesium',
    acronym: 'Mg',
    fullName: 'Magnesium',
    system: 'electrolytes',
    description: 'Mineral cofactor for hundreds of enzymes, muscles, and the heart.',
    purpose: 'Often depleted with diuretics, alcohol use, and chronic PPI therapy.',
    indications: [
      'Refractory hypokalemia',
      'Refractory hypocalcemia',
      'QT prolongation',
      'Alcohol use disorder',
      'Pre-eclampsia / eclampsia',
      'Asthma exacerbation (IV)',
    ],
    range: '0.74–1.07 mmol/L',
    low: 'Hypomagnesemia — diuretics, alcohol, malabsorption, refeeding syndrome, chronic PPI. Often co-exists with low K and low Ca.',
    high: 'Hypermagnesemia — usually renal failure plus Mg-containing antacids / laxatives.',
  },
  {
    id: 'calcium',
    acronym: 'Ca',
    fullName: 'Calcium (total, corrected for albumin)',
    system: 'electrolytes',
    description: 'Mineral essential for bones, nerves, and muscle contraction.',
    purpose: 'Critical for bone, neuromuscular, and cardiac function. Total Ca must be corrected for albumin (or measure ionized Ca directly).',
    indications: [
      'Bone disease (osteoporosis, osteomalacia)',
      'Parathyroid workup',
      'Tetany / paresthesias',
      'Renal failure',
      'Malignancy workup',
      'Vitamin D assessment',
    ],
    range: '2.10–2.55 mmol/L (albumin-corrected) · Ionized: 1.15–1.32 mmol/L',
    low: 'Hypocalcemia — hypoparathyroidism, vitamin D deficiency, CKD, hypomagnesemia, acute pancreatitis.',
    high: 'Hypercalcemia — primary hyperparathyroidism, malignancy (PTHrP, bone metastases), vitamin D toxicity, thiazide diuretics, immobilization.',
  },
  {
    id: 'phosphate',
    acronym: 'PO₄',
    fullName: 'Phosphate',
    system: 'electrolytes',
    description: 'Mineral critical for ATP, DNA, and bone.',
    purpose: 'Often deranged in renal failure, refeeding, and alcoholism.',
    indications: [
      'Renal failure',
      'Refeeding syndrome',
      'Alcohol use disorder',
      'Parathyroid workup',
      'Muscle weakness',
    ],
    range: '0.80–1.45 mmol/L',
    low: 'Hypophosphatemia — refeeding syndrome, alcohol, hyperparathyroidism, vitamin D deficiency, insulin therapy, diuretics. Severe (< 0.3) causes rhabdomyolysis, respiratory failure.',
    high: 'Hyperphosphatemia — renal failure, hypoparathyroidism, vitamin D toxicity, tumor lysis syndrome, rhabdomyolysis.',
  },
  // ============================================================
  // RENAL FUNCTION
  // ============================================================
  {
    id: 'creatinine',
    acronym: 'Cr',
    fullName: 'Creatinine',
    system: 'renal',
    description: 'Waste product made by muscle breakdown, cleared by the kidneys.',
    purpose: 'Used to estimate kidney function (eGFR / CrCl).',
    indications: [
      'Renal function assessment',
      'CKD monitoring',
      'Pre-contrast / pre-op',
      'Drug dosing (many antibiotics, anticoagulants)',
      'AKI workup',
    ],
    range: 'Male: 60–110 μmol/L · Female: 45–90 μmol/L',
    low: 'Low muscle mass (elderly, cachexia), pregnancy, liver disease.',
    high: 'Acute kidney injury (AKI) or chronic kidney disease (CKD). Causes: pre-renal (dehydration, heart failure), renal (ATN, AIN, GN), post-renal (obstruction).',
  },
  {
    id: 'egfr',
    acronym: 'eGFR',
    fullName: 'Estimated Glomerular Filtration Rate',
    system: 'renal',
    description: 'Calculated estimate of kidney filtration capacity.',
    purpose: 'Better than creatinine alone for drug dosing.',
    indications: [
      'CKD staging',
      'Drug dosing',
      'Pre-contrast screening',
      'Routine health screening',
    ],
    range: '≥ 90 mL/min/1.73m² (normal) · 60–89 (mild decline) · 45–59 (mild–moderate) · 30–44 (moderate–severe) · 15–29 (severe) · < 15 (kidney failure)',
    low: 'CKD or AKI. Stage to guide nephrology referral, drug dose adjustment, dialysis planning.',
    high: 'Not clinically significant (pregnancy, hyperfiltration).',
  },
  {
    id: 'urea',
    acronym: 'BUN / Urea',
    fullName: 'Blood Urea Nitrogen / Urea',
    system: 'renal',
    description: 'Nitrogen waste product of protein breakdown, cleared by kidneys.',
    purpose: 'Less specific than creatinine for renal function but useful in pre-renal azotemia.',
    indications: ['Renal function', 'GI bleed workup (elevated with blood digestion)', 'Dehydration'],
    range: '2.5–7.1 mmol/L (urea) · 7–20 mg/dL (BUN)',
    low: 'Liver failure, malnutrition, low protein diet, pregnancy.',
    high: 'Pre-renal azotemia (dehydration, heart failure), renal failure, GI bleed, high-protein diet, catabolic state.',
  },
  {
    id: 'uric-acid',
    acronym: 'UA',
    fullName: 'Uric Acid',
    system: 'renal',
    description: 'End product of purine metabolism, excreted by the kidneys.',
    purpose: 'Elevated in gout, tumor lysis syndrome, and renal impairment.',
    indications: [
      'Gout / hyperuricemia',
      'Tumor lysis syndrome',
      'Renal calculi workup',
      'Pre-chemotherapy baseline',
    ],
    range: 'Male: 208–428 μmol/L · Female: 155–357 μmol/L',
    low: 'Not clinically significant (allopurinol, low purine diet).',
    high: 'Gout, tumor lysis syndrome, renal failure, psoriasis, leukemia, dehydration, thiazide diuretics.',
  },
  {
    id: 'cystatin-c',
    acronym: 'CysC',
    fullName: 'Cystatin C',
    system: 'renal',
    description: 'Low-molecular-weight protein produced by all nucleated cells, freely filtered by the glomerulus.',
    purpose: 'Alternative marker of GFR — less affected by muscle mass or ethnicity than creatinine.',
    indications: ['Confirming reduced GFR when creatinine is borderline', 'Elderly / cachectic patients'],
    range: '0.5–1.3 mg/L (varies by lab)',
    low: 'Not clinically significant.',
    high: 'Reduced GFR — early detection of CKD.',
  },
  // ============================================================
  // HEPATIC FUNCTION
  // ============================================================
  {
    id: 'alt',
    acronym: 'ALT',
    fullName: 'Alanine Aminotransferase',
    system: 'hepatic',
    description: 'Liver enzyme released into the blood when hepatocytes are injured.',
    purpose: 'Sensitive marker of hepatocellular injury.',
    indications: [
      'Liver function assessment',
      'Hepatitis screening',
      'Drug-induced liver injury',
      'Alcohol-related liver disease',
      'Routine health screening',
    ],
    range: '7–55 U/L',
    low: 'Not clinically significant.',
    high: 'Hepatocellular injury — viral hepatitis, alcohol, NAFLD, drugs (acetaminophen, statins, INH), autoimmune hepatitis, ischemic hepatitis.',
  },
  {
    id: 'ast',
    acronym: 'AST',
    fullName: 'Aspartate Aminotransferase',
    system: 'hepatic',
    description: 'Enzyme found in liver, heart, and muscle, released with cell injury.',
    purpose: 'Less specific than ALT — but ratio with ALT helps classify liver disease.',
    indications: ['Liver function (paired with ALT)', 'Muscle injury workup', 'Hemolysis'],
    range: '8–48 U/L',
    low: 'Not clinically significant.',
    high: 'Hepatocellular injury (less specific than ALT) — also: muscle injury (rhabdomyolysis), MI, hemolysis.',
  },
  {
    id: 'alp',
    acronym: 'ALP',
    fullName: 'Alkaline Phosphatase',
    system: 'hepatic',
    description: 'Enzyme found in liver and bone, elevated with cholestasis or bone turnover.',
    purpose: 'Marker of cholestasis or bone disease.',
    indications: [
      'Cholestasis workup',
      'Bone disease (Paget, osteomalacia)',
      'Liver function assessment',
      'Bone metastases screening',
    ],
    range: '40–130 U/L',
    low: 'Not clinically significant (hypothyroidism, zinc deficiency, malnutrition).',
    high: 'Cholestasis (biliary obstruction, primary biliary cholangitis), bone disease (Paget, osteomalacia, healing fracture, metastases), pregnancy (placental ALP).',
  },
  {
    id: 'ggt',
    acronym: 'GGT',
    fullName: 'Gamma-Glutamyl Transferase',
    system: 'hepatic',
    description: 'Liver enzyme sensitive to alcohol and bile duct injury.',
    purpose: 'Sensitive marker of alcohol use and biliary injury.',
    indications: ['Alcohol use workup', 'Cholestasis confirmation', 'Drug-induced liver injury'],
    range: 'Male: 12–64 U/L · Female: 9–36 U/L',
    low: 'Not clinically significant.',
    high: 'Alcohol-related liver disease, cholestasis, drug-induced (phenytoin, carbamazepine, rifampin), NAFLD.',
  },
  {
    id: 'bilirubin',
    acronym: 'Bili',
    fullName: 'Bilirubin (total and direct)',
    system: 'hepatic',
    description: 'Yellow pigment from the breakdown of red blood cells.',
    purpose: 'Routes to direct (conjugated, hepatobiliary) vs indirect (unconjugated, pre-hepatic).',
    indications: [
      'Jaundice workup',
      'Liver function',
      'Hemolysis workup',
      'Newborn jaundice',
    ],
    range: 'Total: 5–21 μmol/L · Direct: < 7 μmol/L',
    low: 'Not clinically significant.',
    high: 'Indirect (unconjugated) — hemolysis, Gilbert syndrome, physiologic neonatal jaundice. Direct (conjugated) — cholestasis, hepatitis, biliary obstruction.',
  },
  {
    id: 'albumin',
    acronym: 'Alb',
    fullName: 'Albumin',
    system: 'hepatic',
    description: 'Main protein made by the liver that carries hormones and holds fluid in the vessels.',
    purpose: 'Reflects liver synthetic function, nutritional status, and fluid status. Long half-life (~20 days).',
    indications: [
      'Liver function assessment',
      'Nutritional assessment',
      'Calcium correction (albumin-corrected Ca)',
      'Fluid status',
      'Disease severity (prognosis in many conditions)',
    ],
    range: '35–50 g/L',
    low: 'Hypoalbuminemia — liver failure, nephrotic syndrome, protein-losing enteropathy, malabsorption, chronic inflammation, burns.',
    high: 'Dehydration, exogenous albumin infusion.',
  },
  {
    id: 'prealbumin',
    acronym: 'Prealbumin',
    fullName: 'Prealbumin (Transthyretin)',
    system: 'hepatic',
    description: 'Short half-life protein made by the liver that transports thyroid hormone and retinol.',
    purpose: 'More sensitive than albumin for acute malnutrition and nutritional recovery.',
    indications: ['Nutritional assessment', 'Refeeding monitoring'],
    range: '150–360 mg/L',
    low: 'Acute malnutrition, hepatic failure, inflammation.',
    high: 'Not clinically significant (renal failure, supplementation).',
  },
  {
    id: 'ammonia',
    acronym: 'NH3',
    fullName: 'Ammonia',
    system: 'hepatic',
    description: 'Nitrogen waste product of protein metabolism, normally converted to urea by the liver.',
    purpose: 'Marker of hepatic encephalopathy and urea cycle disorders.',
    indications: ['Hepatic encephalopathy', 'Unexplained altered mental status', 'Urea cycle disorder workup'],
    range: '15–45 μmol/L',
    low: 'Not clinically significant.',
    high: 'Hepatic encephalopathy, urea cycle disorders, valproic acid toxicity, organic acidemias.',
  },
  // ============================================================
  // LIPID PANEL
  // ============================================================
  {
    id: 'total-cholesterol',
    acronym: 'TC',
    fullName: 'Total Cholesterol',
    system: 'lipid',
    description: 'Sum of all cholesterol carried in the blood.',
    purpose: 'Cardiovascular risk screening.',
    indications: ['Cardiovascular risk assessment', 'Dyslipidemia workup', 'Statin monitoring'],
    range: '< 5.2 mmol/L (desirable)',
    low: 'Malnutrition, hyperthyroidism, liver failure, malabsorption, statin therapy.',
    high: 'Familial hypercholesterolemia, high-fat diet, hypothyroidism, diabetes, nephrotic syndrome, liver disease (cholestasis).',
  },
  {
    id: 'ldl',
    acronym: 'LDL-C',
    fullName: 'Low-Density Lipoprotein Cholesterol',
    system: 'lipid',
    description: 'Atherogenic cholesterol that delivers fat to artery walls.',
    purpose: 'Primary atherogenic particle. Target depends on cardiovascular risk.',
    indications: ['Cardiovascular risk assessment', 'Statin monitoring', 'FH screening'],
    range: '< 3.5 mmol/L (low risk) · < 2.0 mmol/L (high risk / post-MI / diabetes with target organ damage)',
    low: 'Statin / ezetimibe / PCSK9 therapy, malnutrition, liver failure, hyperthyroidism.',
    high: 'Familial hypercholesterolemia, mixed dyslipidemia, metabolic syndrome, hypothyroidism, nephrotic syndrome.',
  },
  {
    id: 'hdl',
    acronym: 'HDL-C',
    fullName: 'High-Density Lipoprotein Cholesterol',
    system: 'lipid',
    description: 'Cholesterol that removes fat from artery walls back to the liver.',
    purpose: '"Good cholesterol" — higher is generally protective.',
    indications: ['Cardiovascular risk assessment', 'Dyslipidemia workup'],
    range: 'Male: > 1.0 mmol/L · Female: > 1.3 mmol/L',
    low: 'Metabolic syndrome, diabetes, smoking, sedentary lifestyle, low-fat diet. Low HDL is a CV risk factor.',
    high: 'Familial hyperalphalipoproteinemia, regular aerobic exercise, moderate alcohol use. Generally protective.',
  },
  {
    id: 'triglycerides',
    acronym: 'TG',
    fullName: 'Triglycerides',
    system: 'lipid',
    description: 'Fat storage molecule carried in the blood for energy.',
    purpose: 'Elevated in metabolic syndrome, diabetes, and pancreatitis risk.',
    indications: ['Cardiovascular risk', 'Pancreatitis workup', 'Metabolic syndrome screening'],
    range: '< 1.7 mmol/L (desirable) · > 10 mmol/L = pancreatitis risk',
    low: 'Malnutrition, hyperthyroidism, malabsorption.',
    high: 'Metabolic syndrome, insulin resistance, diabetes, alcohol, hypothyroidism, pancreatitis (if very high), familial hypertriglyceridemia, certain drugs (steroids, antipsychotics, protease inhibitors).',
  },
  {
    id: 'apo-b',
    acronym: 'ApoB',
    fullName: 'Apolipoprotein B',
    system: 'lipid',
    description: 'Main protein on LDL, VLDL, IDL, and Lp(a) particles — counts total atherogenic particle number.',
    purpose: 'Better CV risk marker than LDL-C in some patients (especially with normal LDL but high triglycerides).',
    indications: ['Cardiovascular risk stratification', 'Statin monitoring', 'Familial hypercholesterolemia'],
    range: '< 0.80 g/L (low risk) · < 0.70 g/L (high risk)',
    low: 'Not clinically significant.',
    high: 'Atherogenic particle burden — increased CV risk, especially in metabolic syndrome / diabetes.',
  },
  {
    id: 'lpa',
    acronym: 'Lp(a)',
    fullName: 'Lipoprotein(a)',
    system: 'lipid',
    description: 'LDL-like particle with an attached apolipoprotein(a) — genetically determined and highly atherogenic.',
    purpose: 'Independent cardiovascular risk factor — once-in-lifetime measurement recommended.',
    indications: ['Family history of premature CAD', 'Atherosclerosis despite controlled LDL', 'Calcified aortic stenosis'],
    range: '< 75 nmol/L (desirable) · < 125 (borderline) · < 450 (moderate) · ≥ 450 (high CV risk)',
    low: 'Healthy.',
    high: 'Increased CV risk — genetic, present in ~20% of the population. Consider PCSK9 inhibitor if already on statin.',
  },
  // ============================================================
  // THYROID
  // ============================================================
  {
    id: 'tsh',
    acronym: 'TSH',
    fullName: 'Thyroid-Stimulating Hormone',
    system: 'thyroid',
    description: 'Pituitary hormone that tells the thyroid to make T4 and T3.',
    purpose: 'First-line screening test for thyroid dysfunction. Inversely related to free T4.',
    indications: [
      'Suspected hypothyroidism / hyperthyroidism',
      'Routine thyroid screening',
      'Levothyroxine dose monitoring',
      'Antithyroid drug monitoring',
      'Atrial fibrillation / unexplained weight change',
    ],
    range: '0.4–4.0 mIU/L (most labs)',
    low: 'Hyperthyroidism (Graves, toxic multinodular goiter, thyroiditis), exogenous thyroid hormone, pituitary suppression. Suppressed (< 0.1) in active hyperthyroidism.',
    high: 'Primary hypothyroidism (Hashimoto, post-thyroidectomy, iodine deficiency), subclinical hypothyroidism, recovery from illness, drug effect (lithium, amiodarone).',
  },
  {
    id: 'ft4',
    acronym: 'Free T4',
    fullName: 'Free Thyroxine',
    system: 'thyroid',
    description: 'Active thyroid hormone that controls metabolism.',
    purpose: 'Paired with TSH to interpret thyroid function.',
    indications: ['Abnormal TSH', 'Pituitary / hypothalamic disease', 'Sick euthyroid workup'],
    range: '9–19 pmol/L (lab-specific)',
    low: 'Hypothyroidism (with high TSH = primary; with low/normal TSH = central). Sick euthyroid.',
    high: 'Hyperthyroidism (with low TSH = primary; with high/normal TSH = TSH-secreting pituitary adenoma or thyroid hormone resistance).',
  },
  {
    id: 'ft3',
    acronym: 'Free T3',
    fullName: 'Free Triiodothyronine',
    system: 'thyroid',
    description: 'Most active thyroid hormone, converted from T4 in tissues.',
    purpose: 'May be elevated in early hyperthyroidism (T3 toxicosis).',
    indications: ['Suspected hyperthyroidism with normal free T4', 'T3 toxicosis workup'],
    range: '3.5–6.5 pmol/L (lab-specific)',
    low: 'Hypothyroidism, sick euthyroid, malnutrition.',
    high: 'T3 toxicosis, hyperthyroidism (especially early Graves).',
  },
  {
    id: 'tpo-ab',
    acronym: 'TPO Ab',
    fullName: 'Anti-Thyroid Peroxidase Antibody',
    system: 'thyroid',
    description: 'Autoantibody against the thyroid peroxidase enzyme.',
    purpose: 'Diagnostic marker for autoimmune thyroid disease (Hashimoto, Graves).',
    indications: ['Elevated TSH', 'Hashimoto workup', 'Pregnancy loss workup'],
    range: '< 35 IU/mL',
    low: 'Healthy.',
    high: 'Hashimoto thyroiditis (most common cause of hypothyroidism), Graves disease, sometimes postpartum thyroiditis.',
  },
  {
    id: 'tg-ab',
    acronym: 'Tg Ab',
    fullName: 'Anti-Thyroglobulin Antibody',
    system: 'thyroid',
    description: 'Autoantibody against thyroglobulin — the storage protein for thyroid hormone.',
    purpose: 'Used as a tumor marker in thyroid cancer follow-up (negates thyroglobulin measurements).',
    indications: ['Thyroid cancer follow-up', 'Hashimoto workup'],
    range: '< 40 IU/mL',
    low: 'Healthy.',
    high: 'Hashimoto thyroiditis, Graves disease, thyroid cancer.',
  },
  {
    id: 'thyroglobulin',
    acronym: 'Tg',
    fullName: 'Thyroglobulin',
    system: 'thyroid',
    description: 'Protein synthesized by thyroid cells — used to monitor thyroid cancer recurrence.',
    purpose: 'Tumor marker in patients who have had thyroidectomy for differentiated thyroid cancer.',
    indications: ['Differentiated thyroid cancer (papillary, follicular) follow-up'],
    range: '< 35 μg/L (no thyroid tissue) — depends on residual tissue',
    low: 'No residual thyroid tissue (after total thyroidectomy + ablation).',
    high: 'Residual or recurrent thyroid cancer.',
  },
  // ============================================================
  // GLUCOSE
  // ============================================================
  {
    id: 'fpg',
    acronym: 'FPG',
    fullName: 'Fasting Plasma Glucose',
    system: 'glucose',
    description: 'Blood sugar level after an 8-hour fast.',
    purpose: 'First-line screening for diabetes and pre-diabetes.',
    indications: [
      'Diabetes screening',
      'Pre-diabetes workup',
      'Diabetes management',
      'Pre-operative',
      'Unexplained polyuria / polydipsia',
    ],
    range: '3.3–5.5 mmol/L (normal) · 5.6–6.9 (impaired fasting glucose) · ≥ 7.0 (diabetes if confirmed)',
    low: 'Hypoglycemia — insulin, sulfonylureas, insulinoma, adrenal insufficiency, sepsis, alcohol.',
    high: 'Prediabetes (5.6–6.9) or diabetes (≥ 7.0). Confirm with repeat or HbA1c.',
  },
  {
    id: 'hba1c',
    acronym: 'HbA1c',
    fullName: 'Glycated Hemoglobin',
    system: 'glucose',
    description: 'Hemoglobin with glucose attached; reflects 3-month average blood sugar.',
    purpose: 'Diagnostic and monitoring test for diabetes.',
    indications: [
      'Diabetes diagnosis',
      'Diabetes monitoring',
      'Pre-diabetes screening',
      'Therapeutic target (most patients: < 7%)',
    ],
    range: '< 5.5% (normal) · 5.5–5.9 (borderline) · 6.0–6.4 (prediabetes) · ≥ 6.5 (diabetes if confirmed)',
    low: 'Hypoglycemia, hemoglobinopathies (sickle cell, thalassemia), recent blood loss, iron deficiency.',
    high: 'Pre-diabetes, diabetes, Cushing syndrome, acromegaly, chronic steroid use, hemochromatosis. Target depends on patient.',
  },
  {
    id: 'fructosamine',
    acronym: 'FrAm',
    fullName: 'Fructosamine',
    system: 'glucose',
    description: 'All serum proteins glycated with glucose — reflects average blood sugar over 2–3 weeks.',
    purpose: 'Shorter-term glycemic index than HbA1c. Useful when HbA1c is unreliable (hemoglobinopathies, recent transfusion).',
    indications: ['Diabetes monitoring when HbA1c unreliable', 'Pregnancy diabetes'],
    range: '205–285 μmol/L (lab-specific)',
    low: 'Hypoglycemia, recent ascorbic acid dose.',
    high: 'Poorly controlled diabetes, hyperglycemia.',
  },
  {
    id: 'c-peptide',
    acronym: 'C-Pep',
    fullName: 'C-Peptide',
    system: 'glucose',
    description: 'Byproduct of endogenous insulin production — marker of pancreatic beta-cell function.',
    purpose: 'Distinguishes endogenous (high) from exogenous insulin (low) hypoglycemia. Monitors insulinoma treatment.',
    indications: ['Hypoglycemia workup', 'Insulinoma diagnosis', 'Type 1 vs type 2 diabetes classification'],
    range: '0.36–1.16 nmol/L (fasting)',
    low: 'Exogenous insulin administration, type 1 diabetes (no endogenous production).',
    high: 'Insulinoma, sulfonylurea use, type 2 diabetes with insulin resistance.',
  },
  // ============================================================
  // IRON STUDIES
  // ============================================================
  {
    id: 'ferritin',
    acronym: 'Ferritin',
    fullName: 'Ferritin',
    system: 'iron',
    description: 'Storage protein that holds iron in reserve inside cells.',
    purpose: 'Best single test for iron deficiency. Acute-phase reactant.',
    indications: [
      'Suspected iron deficiency anemia',
      'Anemia of chronic disease workup',
      'Hemochromatosis screening',
      'Fatigue workup',
      'Restless legs syndrome',
    ],
    range: 'Male: 30–400 μg/L · Female: 15–150 μg/L',
    low: 'Iron deficiency — early marker (precedes anemia). Causes: GI blood loss, menorrhagia, malabsorption (celiac), dietary. < 30 μg/L is diagnostic of iron deficiency.',
    high: 'Acute-phase response (infection, inflammation), hemochromatosis, liver disease, malignancy, hyperthyroidism.',
  },
  {
    id: 'iron',
    acronym: 'Fe',
    fullName: 'Serum Iron',
    system: 'iron',
    description: 'Iron circulating in the blood bound to transferrin.',
    purpose: 'Paired with TIBC and ferritin to interpret iron stores.',
    indications: ['Iron deficiency workup (paired with ferritin and TIBC)', 'Hemochromatosis workup'],
    range: '10–30 μmol/L',
    low: 'Iron deficiency (low Fe, high TIBC, low ferritin), anemia of chronic disease (low Fe, low TIBC, normal/high ferritin).',
    high: 'Hemochromatosis, iron overload (transfusions, hemolysis), liver disease, B6 deficiency, lead poisoning.',
  },
  {
    id: 'tibc',
    acronym: 'TIBC',
    fullName: 'Total Iron-Binding Capacity',
    system: 'iron',
    description: 'Capacity of transferrin to bind iron, indirectly measuring it.',
    purpose: 'High in iron deficiency, low in chronic disease.',
    indications: ['Iron deficiency workup'],
    range: '45–80 μmol/L',
    low: 'Anemia of chronic disease, malnutrition, nephrotic syndrome.',
    high: 'Iron deficiency, pregnancy, oral contraceptive use.',
  },
  {
    id: 'transferrin-saturation',
    acronym: 'TSAT',
    fullName: 'Transferrin Saturation',
    system: 'iron',
    description: 'Percentage of transferrin that is currently carrying iron.',
    purpose: 'Iron ÷ TIBC. Most useful for hemochromatosis screening.',
    indications: ['Hemochromatosis screening', 'Iron overload workup'],
    range: '15–50%',
    low: 'Iron deficiency.',
    high: 'Iron overload — hemochromatosis (often > 45% in men, > 35% in women), iron toxicity.',
  },
  // ============================================================
  // INFLAMMATION
  // ============================================================
  {
    id: 'crp',
    acronym: 'CRP',
    fullName: 'C-Reactive Protein',
    system: 'inflammation',
    description: 'Acute-phase protein released by the liver during inflammation.',
    purpose: 'Sensitive marker of inflammation / infection. Rises within hours.',
    indications: [
      'Bacterial vs viral infection (often)',
      'Inflammatory disease activity (RA, IBD, vasculitis)',
      'Post-op infection surveillance',
      'Cardiovascular risk stratification (hsCRP)',
    ],
    range: '< 5 mg/L (normal) · 5–50 (mild-moderate inflammation) · > 50 (significant — bacterial infection, severe inflammation)',
    low: 'Not clinically significant.',
    high: 'Bacterial infection, autoimmune flare, tissue injury (MI, surgery), malignancy, severe inflammation.',
  },
  {
    id: 'crp-hs',
    acronym: 'hs-CRP',
    fullName: 'High-Sensitivity C-Reactive Protein',
    system: 'cardiac',
    description: 'Ultra-sensitive CRP measured for cardiovascular risk.',
    purpose: 'Cardiovascular risk stratification. Used in primary prevention risk calculators.',
    indications: ['Cardiovascular risk assessment', 'Atypical chest pain risk'],
    range: '< 1.0 mg/L (low risk) · 1.0–3.0 (intermediate) · > 3.0 (high) · > 10 (acute inflammation — re-test in 2 weeks)',
    low: 'Low cardiovascular risk.',
    high: 'Increased cardiovascular risk; consider statin in intermediate-risk patients.',
  },
  {
    id: 'procalcitonin',
    acronym: 'PCT',
    fullName: 'Procalcitonin',
    system: 'inflammation',
    description: 'Pro-hormone of calcitonin — rises in bacterial infection, suppressed in viral.',
    purpose: 'Distinguishes bacterial from viral infection. Guides antibiotic stewardship.',
    indications: ['Sepsis workup', 'Bacterial vs viral pneumonia', 'Antibiotic de-escalation'],
    range: '< 0.10 μg/L (low risk of bacterial infection) · > 0.50 (high risk)',
    low: 'Viral infection, non-infectious inflammation (most of the time).',
    high: 'Bacterial infection, sepsis. Higher values = higher risk of severe infection.',
  },
  // ============================================================
  // CARDIAC
  // ============================================================
  {
    id: 'troponin',
    acronym: 'cTnI / cTnT',
    fullName: 'Cardiac Troponin (high-sensitivity)',
    system: 'cardiac',
    description: 'Heart-muscle protein released into blood with cardiac injury.',
    purpose: 'Gold-standard marker of myocardial injury. Confirms MI when combined with clinical context.',
    indications: ['Suspected acute coronary syndrome', 'Chest pain workup', 'Perioperative MI'],
    range: 'High-sensitivity: < 14 ng/L (URL) · Sex-specific 99th percentile cutoffs. Trend (delta) over 1–3 h matters most.',
    low: 'Not clinically significant.',
    high: 'Acute myocardial infarction (rise and fall), myocarditis, takotsubo cardiomyopathy, PE, severe sepsis, CKD (chronic elevation).',
  },
  {
    id: 'ck',
    acronym: 'CK',
    fullName: 'Creatine Kinase',
    system: 'cardiac',
    description: 'Enzyme in muscle, heart, and brain released with cell injury.',
    purpose: 'Used for rhabdomyolysis and (historically) MI.',
    indications: ['Rhabdomyolysis', 'Muscle injury', 'Statin myopathy', 'MI (older test)'],
    range: 'Male: 39–308 U/L · Female: 26–192 U/L',
    low: 'Not clinically significant (low muscle mass).',
    high: 'Rhabdomyolysis, muscle injury (IM injections, falls, statin), myocarditis, MI, hypothyroidism, strenuous exercise.',
  },
  {
    id: 'ck-mb',
    acronym: 'CK-MB',
    fullName: 'Creatine Kinase MB Isoenzyme',
    system: 'cardiac',
    description: 'Cardiac-specific isoform of creatine kinase.',
    purpose: 'Older MI marker — less specific than troponin. Still used in some settings.',
    indications: ['MI workup (adjunct)', 'Re-infarction assessment'],
    range: '< 5% of total CK (or < 5 U/L)',
    low: 'N/A',
    high: 'Acute MI (peaks earlier than troponin for re-infarction detection).',
  },
  {
    id: 'bnp',
    acronym: 'BNP / NT-proBNP',
    fullName: 'B-Type Natriuretic Peptide',
    system: 'cardiac',
    description: 'Hormone released by the heart when it is stretched or failing.',
    purpose: 'Used to diagnose / rule out heart failure.',
    indications: ['Dyspnea workup', 'Suspected heart failure', 'CHF monitoring'],
    range: 'BNP: < 100 pg/mL (rule out HF) · NT-proBNP: < 125 pg/mL (< 75 y) / < 450 (> 75 y) · Higher in women, lower in obesity',
    low: 'Heart failure unlikely (high negative predictive value).',
    high: 'Heart failure (correlate with echo), pulmonary embolism, COPD exacerbation, renal failure, sepsis.',
  },
  {
    id: 'ldh',
    acronym: 'LDH',
    fullName: 'Lactate Dehydrogenase',
    system: 'cardiac',
    description: 'Enzyme found in many tissues — released with cell injury.',
    purpose: 'Non-specific marker of cell injury. Used for hemolysis, liver, and tumor lysis workup.',
    indications: ['Hemolysis workup', 'Tumor lysis syndrome', 'Acute coronary syndrome (older)', 'Lymphoma / lymphoma monitoring'],
    range: '100–250 U/L',
    low: 'Not clinically significant.',
    high: 'Hemolysis (LDH isoenzymes help), MI, liver disease, malignancy, PE, muscle injury.',
  },
  // ============================================================
  // VITAMINS / MINERALS
  // ============================================================
  {
    id: 'vit-d',
    acronym: '25-OH Vit D',
    fullName: '25-Hydroxyvitamin D',
    system: 'vitamins',
    description: 'Storage form of vitamin D, the best marker of vitamin D status.',
    purpose: 'Best marker of vitamin D status. Stores form (vs 1,25-OH which is active).',
    indications: [
      'Suspected vitamin D deficiency',
      'Osteoporosis workup',
      'Muscle weakness',
      'CKD (informs calcitriol replacement)',
      'Malabsorption',
    ],
    range: '> 75 nmol/L (sufficient) · 50–75 (insufficient) · < 50 (deficient) · < 25 (severe deficiency)',
    low: 'Vitamin D deficiency — seasonal lack of sun, darker skin, malabsorption, obesity, CKD, liver disease. Treat with D3 (cholecalciferol).',
    high: 'Vitamin D toxicity (over-supplementation) — hypercalcemia, nephrocalcinosis.',
  },
  {
    id: 'vit-b12',
    acronym: 'B12',
    fullName: 'Vitamin B12',
    system: 'vitamins',
    description: 'Vitamin essential for nerve function, DNA, and red blood cell production.',
    purpose: 'Essential for nerve function, DNA synthesis, and RBC maturation.',
    indications: [
      'Macrocytic anemia (MCV > 100)',
      'Neurologic symptoms (peripheral neuropathy, memory loss)',
      'Strict vegan / vegetarian screening',
      'Post-bariatric surgery',
      'Metformin use',
      'PPN / H. pylori',
    ],
    range: '> 200 pmol/L (sufficient) · 150–200 (borderline) · < 150 (deficient)',
    low: 'B12 deficiency — dietary (vegan), pernicious anemia (anti-IF antibodies), atrophic gastritis, metformin, PPI, malabsorption (Crohn, celiac, ileal resection).',
    high: 'Usually not clinically significant (liver disease, leukemia, supplements).',
  },
  {
    id: 'folate',
    acronym: 'Fol',
    fullName: 'Folate (serum + RBC)',
    system: 'vitamins',
    description: 'Vitamin essential for DNA synthesis and cell division.',
    purpose: 'Essential for DNA synthesis. Deficiency causes macrocytic anemia.',
    indications: [
      'Macrocytic anemia',
      'Pregnancy planning',
      'Alcohol use disorder',
      'Malnutrition',
      'Methotrexate monitoring',
    ],
    range: 'Serum: > 10 nmol/L · RBC folate: > 320 nmol/L (better marker of tissue stores)',
    low: 'Folate deficiency — poor diet, alcohol, malabsorption, hemolysis, certain drugs (methotrexate, trimethoprim, phenytoin).',
    high: 'Usually not clinically significant (supplementation).',
  },
  {
    id: 'mma',
    acronym: 'MMA',
    fullName: 'Methylmalonic Acid',
    system: 'vitamins',
    description: 'Metabolite that accumulates when vitamin B12 is low.',
    purpose: 'More specific than B12 level alone for B12 deficiency (vs folate deficiency).',
    indications: ['Borderline B12', 'Unexplained neuropathy with normal B12'],
    range: '< 0.40 μmol/L',
    low: 'Not clinically significant.',
    high: 'B12 deficiency (specifically — not elevated in folate deficiency). Also: renal failure, MMAemia (rare).',
  },
  {
    id: 'vit-a',
    acronym: 'Vit A',
    fullName: 'Vitamin A (Retinol)',
    system: 'vitamins',
    description: 'Fat-soluble vitamin essential for vision, immunity, and epithelial integrity.',
    purpose: 'Diagnoses deficiency or toxicity. Modified in pregnancy and liver disease.',
    indications: ['Night blindness', 'Malabsorption', 'Suspected toxicity (megavitamin use)'],
    range: '1.05–2.45 μmol/L',
    low: 'Deficiency — night blindness, dry skin, infection risk. Causes: malabsorption, poor diet.',
    high: 'Toxicity — hepatotoxicity, increased intracranial pressure, bone resorption. Common with high-dose supplements.',
  },
  {
    id: 'vit-e',
    acronym: 'Vit E',
    fullName: 'Vitamin E (Alpha-Tocopherol)',
    system: 'vitamins',
    description: 'Fat-soluble antioxidant.',
    purpose: 'Deficiency in fat malabsorption (cystic fibrosis, cholestasis).',
    indications: ['Malabsorption', 'Neurologic symptoms of unknown cause'],
    range: '12–46 μmol/L',
    low: 'Deficiency — neurologic (spinocerebellar ataxia), hemolytic anemia. CF, cholestasis, abetalipoproteinemia.',
    high: 'Megavitamin use — may impair coagulation.',
  },
  {
    id: 'vit-b1',
    acronym: 'B1',
    fullName: 'Thiamine (Vitamin B1)',
    system: 'vitamins',
    description: 'Cofactor for energy metabolism in the brain and nerves.',
    purpose: 'Diagnoses Wernicke encephalopathy in at-risk patients.',
    indications: ['Alcohol use disorder', 'Wernicke encephalopathy', 'Refeeding syndrome', 'Post-bariatric surgery'],
    range: '70–180 nmol/L',
    low: 'Thiamine deficiency — Wernicke encephalopathy (confusion, ataxia, ophthalmoplegia), beriberi. Always give before glucose in at-risk patients.',
    high: 'Not clinically significant.',
  },
  {
    id: 'zinc',
    acronym: 'Zn',
    fullName: 'Zinc',
    system: 'vitamins',
    description: 'Trace mineral essential for wound healing, immune function, and taste.',
    purpose: 'Diagnoses deficiency or toxicity.',
    indications: ['Wound healing problems', 'Recurrent infections', 'Taste / smell changes', 'Chronic diarrhea', 'TPN monitoring'],
    range: '10–18 μmol/L',
    low: 'Deficiency — poor wound healing, hair loss, dysgeusia, immune dysfunction.',
    high: 'Toxicity (rare) — nausea, copper deficiency, vomiting.',
  },
  {
    id: 'copper',
    acronym: 'Cu',
    fullName: 'Copper',
    system: 'vitamins',
    description: 'Trace mineral essential for enzymes, RBC formation, and nerve function.',
    purpose: 'Diagnoses Wilson disease (high) or deficiency (low).',
    indications: ['Wilson disease workup', 'Liver disease of unknown cause', 'TPN monitoring'],
    range: '11–22 μmol/L',
    low: 'Deficiency — anemia, neutropenia, neurologic symptoms, Menkes disease.',
    high: 'Wilson disease, primary biliary cholangitis, excess supplementation.',
  },
  // ============================================================
  // TOXICOLOGY / DRUG LEVELS
  // ============================================================
  {
    id: 'digoxin',
    acronym: 'Dig',
    fullName: 'Digoxin',
    system: 'toxicology',
    description: 'Cardiac glycoside that increases contractility and slows AV conduction.',
    purpose: 'Toxicity is common in renal impairment, especially with hypokalemia.',
    indications: ['Routine monitoring', 'Suspected toxicity (visual changes, nausea, arrhythmias)'],
    range: '0.6–2.0 nmol/L (trough, 12–24 h post-dose)',
    low: 'Subtherapeutic — heart failure inadequately controlled.',
    high: 'Toxicity — visual halos, nausea, every arrhythmia imaginable. Stop drug, correct K+, consider digoxin immune Fab.',
  },
  {
    id: 'lithium',
    acronym: 'Li',
    fullName: 'Lithium',
    system: 'toxicology',
    description: 'Mood stabilizer used in bipolar disorder.',
    purpose: 'Narrow therapeutic window — toxicity can be life-threatening.',
    indications: ['Routine monitoring', 'Suspected toxicity (tremor, confusion, ataxia, seizures)'],
    range: '0.6–1.2 mmol/L (maintenance) · 0.8–1.0 (acute mania) · > 1.5 = toxic',
    low: 'Subtherapeutic.',
    high: 'Toxicity — tremor, ataxia, confusion, seizures, renal failure. Hold dose, IV fluids, consider hemodialysis if > 2.5.',
  },
  {
    id: 'phenytoin',
    acronym: 'PHT',
    fullName: 'Phenytoin',
    system: 'toxicology',
    description: 'Anticonvulsant — sodium channel blocker.',
    purpose: 'Therapeutic drug monitoring. Zero-order kinetics — small dose changes cause large level changes.',
    indications: ['Routine monitoring', 'Seizure breakthroughs', 'Suspected toxicity (nystagmus, ataxia, gingival hyperplasia)'],
    range: '40–80 μmol/L (total). 4–8 μg/mL (total, reported units).',
    low: 'Subtherapeutic — seizure risk.',
    high: 'Toxicity — nystagmus, ataxia, diplopia, confusion, gingival hyperplasia, hirsutism with chronic use.',
  },
  {
    id: 'phenobarbital',
    acronym: 'PHB',
    fullName: 'Phenobarbital',
    system: 'toxicology',
    description: 'Long-acting barbiturate anticonvulsant.',
    purpose: 'Therapeutic drug monitoring — long half-life.',
    indications: ['Routine monitoring', 'Seizure control assessment'],
    range: '65–170 μmol/L',
    low: 'Subtherapeutic.',
    high: 'Sedation, respiratory depression, coma in overdose.',
  },
  {
    id: 'theophylline',
    acronym: 'Theo',
    fullName: 'Theophylline',
    system: 'toxicology',
    description: 'Methylxanthine bronchodilator — narrow therapeutic window.',
    purpose: 'Monitoring (rarely used now). Toxicity causes seizures and arrhythmias.',
    indications: ['Routine monitoring', 'Intoxication workup'],
    range: '55–110 μmol/L (10–20 μg/mL)',
    low: 'Subtherapeutic.',
    high: 'Toxicity — nausea, tachycardia, seizures, arrhythmias. Caution: many drug interactions.',
  },
  {
    id: 'valproate',
    acronym: 'VPA',
    fullName: 'Valproic Acid',
    system: 'toxicology',
    description: 'Anticonvulsant and mood stabilizer.',
    purpose: 'Therapeutic drug monitoring. Hepatotoxic and pancreatic toxic at high levels.',
    indications: ['Routine monitoring', 'Seizure breakthroughs', 'Hepatotoxicity workup'],
    range: '350–700 μmol/L',
    low: 'Subtherapeutic.',
    high: 'Hepatotoxicity, thrombocytopenia, pancreatitis, CNS depression.',
  },
  {
    id: 'carbamazepine',
    acronym: 'CBZ',
    fullName: 'Carbamazepine',
    system: 'toxicology',
    description: 'Anticonvulsant for partial seizures and trigeminal neuralgia.',
    purpose: 'Therapeutic drug monitoring. Induces many CYP enzymes — multiple drug interactions.',
    indications: ['Routine monitoring', 'Toxicity (ataxia, nystagmus, hyponatremia)'],
    range: '17–51 μmol/L (4–12 μg/mL)',
    low: 'Subtherapeutic.',
    high: 'Toxicity — ataxia, nystagmus, diplopia, SIADH with hyponatremia, rare agranulocytosis.',
  },
  {
    id: 'acetaminophen',
    acronym: 'APAP',
    fullName: 'Acetaminophen',
    system: 'toxicology',
    description: 'Common analgesic / antipyretic. Toxic dose > 150 mg/kg.',
    purpose: 'Acetaminophen toxicity is the most common cause of acute liver failure.',
    indications: ['Suspected overdose', 'Staged workup with Rumack-Matthew nomogram'],
    range: 'Therapeutic: 65–200 μmol/L (10–30 μg/mL) · Toxic: > 1000 μmol/L at 4 h post-ingestion',
    low: 'N/A',
    high: 'Hepatotoxicity risk — use Rumack-Matthew nomogram. Treat with N-acetylcysteine (NAC) within 8–10 h of ingestion.',
  },
  {
    id: 'salicylate',
    acronym: 'ASA',
    fullName: 'Salicylate (Aspirin)',
    system: 'toxicology',
    description: 'Analgesic, antiplatelet. Toxic in overdose with mixed acid-base disturbance.',
    purpose: 'Salicylate toxicity can be acute or chronic (last is harder to diagnose).',
    indications: ['Suspected overdose', 'Toxic ingestion workup'],
    range: 'Therapeutic: 0.7–2.2 mmol/L (analgesic) · 0.1–0.3 mmol/L (antiplatelet) · Toxic: > 2.5 mmol/L',
    low: 'Not clinically significant.',
    high: 'Tinnitus, hyperthermia, hyperventilation, mixed metabolic acidosis + respiratory alkalosis. Treatment: IV bicarbonate, hemodialysis for severe.',
  },
  {
    id: 'methanol',
    acronym: 'MeOH',
    fullName: 'Methanol',
    system: 'toxicology',
    description: 'Toxic alcohol — metabolized to formic acid (causes blindness and acidosis).',
    purpose: 'Diagnoses toxic alcohol ingestion.',
    indications: ['Suspected toxic alcohol ingestion', 'Unexplained anion gap metabolic acidosis'],
    range: '0 mmol/L (none detectable)',
    low: 'N/A',
    high: 'Visual disturbances, blindness, anion gap metabolic acidosis, seizures. Treat with fomepizole or ethanol + hemodialysis.',
  },
  {
    id: 'ethanol',
    acronym: 'EtOH',
    fullName: 'Ethanol (Blood Alcohol)',
    system: 'toxicology',
    description: 'Ethyl alcohol blood level — used for clinical and legal assessment.',
    purpose: 'Quantifies intoxication and impairment.',
    indications: ['Acute intoxication', 'ED assessment', 'Impaired driving assessment'],
    range: '0 mmol/L (sober)',
    low: 'N/A',
    high: '> 4.3 mmol/L (20 mmol/L) = risk of respiratory depression, aspiration. > 65 mmol/L can be fatal.',
  },
  // ============================================================
  // ROUTINE URINALYSIS
  // ============================================================
  {
    id: 'ua-routine',
    acronym: 'UA',
    fullName: 'Urinalysis (Routine Dipstick + Microscopic)',
    system: 'urine',
    description: 'Urinalysis — physical, chemical, and microscopic exam of urine.',
    purpose: 'Screens for urinary tract, kidney, metabolic, and systemic diseases.',
    indications: ['Dysuria, frequency, urgency', 'Flank pain', 'Hematuria', 'Diabetes monitoring', 'Pregnancy tests', 'Routine health check', 'Unexplained fever'],
    range: 'See individual components',
    low: 'N/A',
    high: 'See individual components.',
  },
  {
    id: 'ua-glucose',
    acronym: 'Glu (UA)',
    fullName: 'Urine Glucose',
    system: 'urine',
    description: 'Dipstick detection of glucose in urine.',
    purpose: 'Screens for hyperglycemia. Glycosuria occurs when blood glucose > 10 mmol/L (renal threshold).',
    indications: ['Diabetes screening', 'Diabetes monitoring'],
    range: 'Negative',
    low: 'N/A',
    high: 'Diabetes mellitus, pregnancy, glucosuria without hyperglycemia (Fanconi syndrome, SGLT2 inhibitors).',
  },
  {
    id: 'ua-blood',
    acronym: 'Blood (UA)',
    fullName: 'Urine Blood (Hematuria)',
    system: 'urine',
    description: 'Dipstick detection of blood in urine (RBCs, free hemoglobin, or myoglobin).',
    purpose: 'Screens for urinary tract, kidney, and systemic disease.',
    indications: ['Hematuria', 'Dysuria', 'Flank pain', 'Anemia workup', 'Glomerular disease follow-up'],
    range: 'Negative',
    low: 'N/A',
    high: 'UTI, stones, bladder/kidney cancer, glomerulonephritis, trauma, myoglobinuria (rhabdomyolysis), menstruation (false positive).',
  },
  {
    id: 'ua-protein',
    acronym: 'Prot (UA)',
    fullName: 'Urine Protein',
    system: 'urine',
    description: 'Dipstick detection of protein in urine.',
    purpose: 'Screens for kidney disease, especially when paired with albumin (microalbumin).',
    indications: ['CKD screening', 'Diabetes monitoring', 'Glomerular disease', 'Pre-eclampsia'],
    range: 'Negative (or trace)',
    low: 'N/A',
    high: 'Glomerular disease (proteinuria), tubular disease (low-molecular-weight protein), overflow (multiple myeloma), postural, fever, exercise.',
  },
  {
    id: 'ua-nitrite',
    acronym: 'Nit',
    fullName: 'Urine Nitrite',
    system: 'urine',
    description: 'Dipstick test for nitrite — produced by bacteria that convert nitrate to nitrite.',
    purpose: 'Screens for urinary tract infection (especially gram-negative organisms).',
    indications: ['Suspected UTI', 'Dysuria, frequency, urgency'],
    range: 'Negative',
    low: 'N/A',
    high: 'Bacterial UTI (E. coli, Klebsiella, Proteus). False negative if bladder dwell time < 4 h or non-nitrite-producing organism (Enterococcus, Pseudomonas).',
  },
  {
    id: 'ua-le',
    acronym: 'LE',
    fullName: 'Urine Leukocyte Esterase',
    system: 'urine',
    description: 'Dipstick test for leukocyte esterase — enzyme from neutrophils.',
    purpose: 'Screens for pyuria (suggesting UTI).',
    indications: ['Suspected UTI', 'Dysuria, frequency, urgency'],
    range: 'Negative',
    low: 'N/A',
    high: 'Pyuria — UTI, pyelonephritis, STI, kidney stones, interstitial nephritis.',
  },
  {
    id: 'ua-ketones',
    acronym: 'Ket',
    fullName: 'Urine Ketones',
    system: 'urine',
    description: 'Dipstick detection of ketones (acetoacetate, acetone).',
    purpose: 'Screens for ketonuria from DKA, starvation, or ketogenic diet.',
    indications: ['DKA workup', 'Nausea / vomiting in diabetic', 'Unexplained acidosis', 'Weight loss'],
    range: 'Negative',
    low: 'N/A',
    high: 'DKA, prolonged fasting, alcoholic ketoacidosis, prolonged vomiting, ketogenic diet.',
  },
  {
    id: 'ua-bilirubin',
    acronym: 'Bili (UA)',
    fullName: 'Urine Bilirubin',
    system: 'urine',
    description: 'Dipstick detection of conjugated bilirubin in urine.',
    purpose: 'Screens for conjugated hyperbilirubinemia (hepatobiliary disease).',
    indications: ['Jaundice workup', 'Liver disease'],
    range: 'Negative',
    low: 'N/A',
    high: 'Conjugated hyperbilirubinemia — hepatitis, biliary obstruction. Unconjugated bilirubin does NOT appear in urine (hemolysis, Gilbert syndrome).',
  },
  {
    id: 'ua-urobilinogen',
    acronym: 'UBG',
    fullName: 'Urine Urobilinogen',
    system: 'urine',
    description: 'Product of bilirubin breakdown by gut bacteria, excreted in urine.',
    purpose: 'Screens for liver and hemolytic disease.',
    indications: ['Jaundice workup', 'Hemolysis workup'],
    range: '0.2–1.0 EU/dL (normal)',
    low: 'Biliary obstruction (no bilirubin reaching the gut).',
    high: 'Hemolysis (increased bilirubin production), hepatitis.',
  },
  {
    id: 'ua-ph',
    acronym: 'pH (UA)',
    fullName: 'Urine pH',
    system: 'urine',
    description: 'Measure of urine acidity.',
    purpose: 'Part of acid-base and stone risk assessment.',
    indications: ['Renal tubular acidosis workup', 'Stone-former workup', 'Acid-base assessment'],
    range: '4.5–8.0',
    low: 'Acidic — metabolic acidosis, COPD, high-protein diet, uric acid stones.',
    high: 'Alkaline — RTA, UTI with urease-producing organism (Proteus), vegetarian diet, renal tubular acidosis.',
  },
  {
    id: 'ua-sg',
    acronym: 'SG',
    fullName: 'Urine Specific Gravity',
    system: 'urine',
    description: 'Reflects urine concentration (particles vs water).',
    purpose: 'Screens for hydration status and concentrating ability.',
    indications: ['Dehydration', 'SIADH / DI', 'Renal concentrating ability'],
    range: '1.003–1.030',
    low: 'Overhydration, diabetes insipidus, chronic renal failure.',
    high: 'Dehydration, glycosuria, proteinuria, SIADH.',
  },
  {
    id: 'ua-ob',
    acronym: 'OB',
    fullName: 'Urine Occult Blood',
    system: 'urine',
    description: 'Dipstick test for blood that may not be visible to the eye.',
    purpose: 'Screens for microscopic hematuria or myoglobinuria.',
    indications: ['Anemia workup', 'Unexplained fatigue', 'Family history of renal disease', 'FOBT screening'],
    range: 'Negative',
    low: 'N/A',
    high: 'Microscopic hematuria (stones, cancer, GN), myoglobinuria (rhabdomyolysis).',
  },
  {
    id: 'microalb',
    acronym: 'Microalb',
    fullName: 'Microalbumin (ACR)',
    system: 'urine',
    description: 'Albumin-to-creatinine ratio in urine — earliest marker of diabetic kidney disease.',
    purpose: 'Screens for early diabetic nephropathy when total proteinuria is still normal.',
    indications: ['Annual diabetes screening', 'CKD monitoring', 'Hypertension with kidney involvement'],
    range: '< 3 mg/mmol (normal) · 3–30 (moderately increased — microalbuminuria) · > 30 (severely increased — macroalbuminuria)',
    low: 'Healthy.',
    high: 'Diabetic nephropathy (early), hypertensive nephrosclerosis, glomerular disease. Initiate ACE-I/ARB if persistent.',
  },
  {
    id: 'urine-creat',
    acronym: 'uCr',
    fullName: 'Urine Creatinine',
    system: 'urine',
    description: 'Used to correct spot urine levels for concentration variation.',
    purpose: 'Denominator for protein/creatinine and albumin/creatinine ratios.',
    indications: ['Always paired with protein or albumin', '24-hour collection volume check'],
    range: 'Variable (4.0–22.0 mmol/L in spot urine)',
    low: 'Very dilute urine.',
    high: 'Very concentrated urine.',
  },
  // ============================================================
  // URINALYSIS 24-HOUR
  // ============================================================
  {
    id: '24h-albumin',
    acronym: '24h Alb',
    fullName: '24-Hour Urine Albumin',
    system: 'urine',
    description: 'Total albumin excreted in 24 hours.',
    purpose: 'More accurate than spot urine for quantifying kidney protein loss.',
    indications: ['Quantifying proteinuria', 'Nephrotic syndrome workup'],
    range: '< 30 mg/24h (normal) · 30–300 (microalbuminuria) · > 300 (macroalbuminuria)',
    low: 'Healthy.',
    high: 'Glomerular disease — diabetic nephropathy, FSGS, membranous, etc.',
  },
  {
    id: '24h-protein',
    acronym: '24h Prot',
    fullName: '24-Hour Urine Protein',
    system: 'urine',
    description: 'Total protein excreted in 24 hours — gold standard for proteinuria.',
    purpose: 'Quantifies daily protein loss.',
    indications: ['Nephrotic syndrome workup', 'Unexplained proteinuria'],
    range: '< 150 mg/24h',
    low: 'Healthy.',
    high: 'Nephrotic-range (> 3.5 g/24h) = severe glomerular disease. Sub-nephrotic = tubular interstitial disease.',
  },
  {
    id: '24h-calcium',
    acronym: '24h Ca',
    fullName: '24-Hour Urine Calcium',
    system: 'urine',
    description: 'Total calcium excreted in 24 hours.',
    purpose: 'Used for stone-former workup and parathyroid assessment.',
    indications: ['Kidney stone workup', 'Hyperparathyroidism', 'Hypercalcemia workup'],
    range: '2.5–7.5 mmol/24h (varies by diet)',
    low: 'Hypocalciuria — hypoparathyroidism, vitamin D deficiency, malabsorption.',
    high: 'Hypercalciuria — hyperparathyroidism, sarcoidosis, idiopathic, stone-former risk.',
  },
  {
    id: '24h-oxalate',
    acronym: '24h Ox',
    fullName: '24-Hour Urine Oxalate',
    system: 'urine',
    description: 'Total oxalate excreted in 24 hours.',
    purpose: 'Stone-former workup — high oxalate promotes calcium oxalate stones.',
    indications: ['Recurrent kidney stones'],
    range: '< 0.5 mmol/24h',
    low: 'Healthy.',
    high: 'Enteric hyperoxaluria (Crohn, short bowel, bariatric surgery), primary hyperoxaluria, high-oxalate diet.',
  },
  {
    id: '24h-citrate',
    acronym: '24h Cit',
    fullName: '24-Hour Urine Citrate',
    system: 'urine',
    description: 'Citrate excreted in urine — a stone inhibitor.',
    purpose: 'Low citrate is a treatable cause of calcium stones.',
    indications: ['Recurrent kidney stones', 'Metabolic acidosis workup'],
    range: '> 1.6 mmol/24h (protective)',
    low: 'Hypocitraturia — distal RTA, chronic diarrhea, low-fruit diet, idiopathic. Promotes calcium stones.',
    high: 'Not clinically significant (alkalosis).',
  },
  {
    id: '24h-uric',
    acronym: '24h UA',
    fullName: '24-Hour Urine Uric Acid',
    system: 'urine',
    description: 'Total uric acid excreted in 24 hours.',
    purpose: 'Stone-former workup — high uric acid causes uric acid stones.',
    indications: ['Recurrent kidney stones', 'Gout'],
    range: '< 4.5 mmol/24h',
    low: 'Healthy.',
    high: 'Hyperuricosuria — gout, Lesch-Nyhan, high-purine diet, tumor lysis.',
  },
  {
    id: '24h-cortisol',
    acronym: '24h F',
    fullName: '24-Hour Urine Free Cortisol',
    system: 'toxicology',
    description: 'Unbound cortisol excreted in urine over 24 hours — best screening test for Cushing syndrome.',
    purpose: 'Screens for endogenous Cushing syndrome.',
    indications: ['Suspected Cushing syndrome', 'Adrenal incidentaloma'],
    range: '< 220 nmol/24h',
    low: 'Adrenal insufficiency (Addison disease).',
    high: 'Cushing syndrome — pituitary, adrenal, or ectopic ACTH. Confirm with dexamethasone suppression test.',
  },
  {
    id: '24h-metanephrines',
    acronym: '24h Meta',
    fullName: '24-Hour Urine Metanephrines',
    system: 'toxicology',
    description: 'Catecholamine metabolites collected over 24 hours.',
    purpose: 'Screens for pheochromocytoma.',
    indications: ['Suspected pheochromocytoma', 'Refractory hypertension with spells'],
    range: '< 5.0 μmol/24h (metanephrines + normetanephrines — lab-specific)',
    low: 'Not clinically significant.',
    high: 'Pheochromocytoma / paraganglioma — confirm with plasma fractionated metanephrines and imaging.',
  },
  {
    id: '24h-cortisol-creat',
    acronym: 'ACR',
    fullName: 'Albumin-to-Creatinine Ratio (ACR)',
    system: 'urine',
    description: 'Spot urine ratio of albumin to creatinine — corrects for concentration.',
    purpose: 'Replaces 24-hour collections for routine diabetic nephropathy screening.',
    indications: ['Annual diabetes screening', 'CKD monitoring'],
    range: '< 3 mg/mmol (normal) · 3–30 (microalbuminuria) · > 30 (macroalbuminuria)',
    low: 'Healthy.',
    high: 'Early diabetic nephropathy, hypertensive nephrosclerosis, glomerular disease.',
  },
  {
    id: 'creat-clear',
    acronym: 'CrCl',
    fullName: 'Creatinine Clearance (24-hour)',
    system: 'renal',
    description: '24-hour urine creatinine + serum creatinine used to estimate GFR.',
    purpose: 'Direct measurement of GFR — more accurate than eGFR for drug dosing in select patients.',
    indications: ['Drug dosing (especially chemo)', 'CKD with abnormal muscle mass', 'Pregnancy'],
    range: '> 90 mL/min (normal) · 60–89 (mild decline) · 30–59 (moderate) · 15–29 (severe) · < 15 (failure)',
    low: 'CKD or AKI.',
    high: 'Pregnancy, hyperfiltration.',
  },
  {
    id: 'gfr-measured',
    acronym: 'mGFR',
    fullName: 'Measured GFR (Nuclear / Iothalamate)',
    system: 'renal',
    description: 'Direct measurement of GFR using a tracer (iothalamate-I125, Tc-99m DTPA, or EDTA).',
    purpose: 'Most accurate measurement of GFR — used when eGFR is unreliable (extremes of body size, amputation, paraplegia).',
    indications: ['Potential live kidney donor assessment', 'Drug dosing critical', 'Discrepancy between eGFR and clinical picture'],
    range: '> 90 mL/min/1.73m² (normal) — varies by method',
    low: 'CKD or AKI.',
    high: 'Pregnancy, hyperfiltration.',
  },
  // ============================================================
  // MICROBIOLOGY
  // ============================================================
  {
    id: 'blood-culture',
    acronym: 'BCx',
    fullName: 'Blood Culture',
    system: 'microbiology',
    description: 'Blood incubated in culture media to grow bacteria or fungi.',
    purpose: 'Diagnoses bloodstream infection (bacteremia, fungemia).',
    indications: ['Fever with suspected sepsis', 'Endocarditis', 'Catheter infection', 'Unexplained fever in immunocompromised'],
    range: 'No growth after 5 days',
    low: 'N/A',
    high: 'Identification of a pathogen with antibiotic sensitivities — tailor antimicrobial therapy.',
  },
  {
    id: 'urine-culture',
    acronym: 'UCx',
    fullName: 'Urine Culture',
    system: 'microbiology',
    description: 'Urine incubated to grow bacteria.',
    purpose: 'Diagnoses UTI and identifies organism + sensitivities.',
    indications: ['Suspected UTI', 'Recurrent UTI', 'Pregnancy screening', 'Pre-urologic procedure'],
    range: '< 10⁴ CFU/L (no significant growth) · > 10⁵ (significant)',
    low: 'No growth / sterile.',
    high: 'Bacterial identification (E. coli, Klebsiella, Proteus, Enterococcus) with sensitivities.',
  },
  {
    id: 'stool-culture',
    acronym: 'SCx',
    fullName: 'Stool Culture',
    system: 'microbiology',
    description: 'Stool inoculated onto selective media to grow enteric pathogens.',
    purpose: 'Diagnoses invasive bacterial diarrhea (Salmonella, Shigella, Campylobacter, E. coli O157:H7).',
    indications: ['Bloody diarrhea', 'Fever', 'Diarrhea in immunocompromised', 'Outbreak investigation', 'Public health reporting'],
    range: 'No enteric pathogens isolated',
    low: 'N/A',
    high: 'Pathogen identified (Salmonella, Shigella, Campylobacter, E. coli O157:H7, Yersinia).',
  },
  {
    id: 'stool-oandp',
    acronym: 'O&P',
    fullName: 'Stool Ova and Parasites',
    system: 'microbiology',
    description: 'Microscopic examination of stool for parasites and their eggs.',
    purpose: 'Diagnoses parasitic intestinal infection.',
    indications: ['Persistent diarrhea (> 7 days)', 'Recent travel to endemic area', 'Immunocompromised with diarrhea', 'Eosinophilia + GI symptoms'],
    range: 'No ova or parasites seen',
    low: 'N/A',
    high: 'Identification of parasites (Giardia, Entamoeba, Cryptosporidium, etc.).',
  },
  {
    id: 'stool-cd',
    acronym: 'C. diff',
    fullName: 'Clostridioides difficile Toxin / PCR',
    system: 'microbiology',
    description: 'Detection of C. difficile toxin or toxin gene in stool.',
    purpose: 'Diagnoses C. difficile infection (pseudomembranous colitis).',
    indications: ['Diarrhea after recent antibiotic use', 'Hospital-acquired diarrhea', '≥ 3 unformed stools / 24 h'],
    range: 'Negative',
    low: 'N/A',
    high: 'C. difficile infection — treat with oral vancomycin or fidaxomicin. Stop offending antibiotic if possible.',
  },
  {
    id: 'fobt',
    acronym: 'FOBT',
    fullName: 'Fecal Occult Blood Test',
    system: 'microbiology',
    description: 'Detects invisible blood in stool — used for colorectal cancer screening.',
    purpose: 'Screens for colorectal cancer and other GI bleeding lesions.',
    indications: ['Colorectal cancer screening (age 50+)', 'Unexplained iron deficiency anemia'],
    range: 'Negative',
    low: 'N/A',
    high: 'GI bleeding — colon cancer, polyps, IBD, ulcers, hemorrhoids. Confirm with colonoscopy if positive.',
  },
  {
    id: 'covid-pcr',
    acronym: 'SARS-CoV-2 PCR',
    fullName: 'SARS-CoV-2 PCR',
    system: 'microbiology',
    description: 'Nucleic acid amplification test for SARS-CoV-2 from nasopharyngeal or other swab.',
    purpose: 'Diagnoses active COVID-19 infection.',
    indications: ['Suspected COVID-19', 'Pre-admission screening', 'Outbreak investigation'],
    range: 'Negative / Not detected',
    low: 'N/A',
    high: 'COVID-19 infection — report to public health, isolate, consider treatment if high-risk.',
  },
  {
    id: 'rpr',
    acronym: 'RPR',
    fullName: 'Rapid Plasma Reagin (Syphilis Screen)',
    system: 'serology',
    description: 'Non-treponemal screening test for syphilis — detects antibodies against cardiolipin-cholesterol-lecithin antigen.',
    purpose: 'Screens for syphilis. Titer used to monitor treatment response.',
    indications: ['Pregnancy screening', 'STI workup', 'HIV workup', 'Annual MSM screening'],
    range: 'Non-reactive (negative)',
    low: 'N/A',
    high: 'Reactive — confirm with TP-PA / FTA-ABS. Titer > 1:1 indicates past or current syphilis. Four-fold drop over 6–12 months indicates treatment success.',
  },
];

export const labSystems: { id: LabSystem; label: string }[] = [
  { id: 'hematology', label: 'Hematology (CBC)' },
  { id: 'coagulation', label: 'Coagulation' },
  { id: 'electrolytes', label: 'Electrolytes' },
  { id: 'renal', label: 'Renal function' },
  { id: 'hepatic', label: 'Liver function' },
  { id: 'lipid', label: 'Lipid panel' },
  { id: 'thyroid', label: 'Thyroid' },
  { id: 'glucose', label: 'Glucose' },
  { id: 'iron', label: 'Iron studies' },
  { id: 'inflammation', label: 'Inflammation' },
  { id: 'cardiac', label: 'Cardiac' },
  { id: 'vitamins', label: 'Vitamins & minerals' },
  { id: 'toxicology', label: 'Toxicology / drug levels' },
  { id: 'urine', label: 'Urinalysis & urine chemistry' },
  { id: 'microbiology', label: 'Microbiology' },
  { id: 'serology', label: 'Serology' },
];
